title: "Luke Waldron"
description: "Insight Manager | Data Science | FCA & FOS Complaints (UK Banking)"
theme: jekyll-theme-slate

# Optional header image
logo: /Images/9F2B252D-4D27-469D-A35A-E5D706C4B82B.jpeg

# Show download button automatically
show_downloads: true

# GitHub Pages metadata
github:
  is_project_page: false

